### ISSUE TITLE
Memory Allocation Optimization

### ISSUE THREAD

**Issue by sheacloud** [vmware/go-ipfix#100]
**Is your feature request related to a problem? Please describe.**
Currently go-ipfix takes in the blank interface for the API used to create InformationElements, and many of the functions which get called when adding IEs to records, encoding the records, etc also go through blank interface parameters. This results in a large number of objects being allocated to the heap during flow record creation (most times the compiler puts blank interface parameters on the heap), resulting in a large garbage collection overhead.
In my testing (more details on the test scenario in **Additional context**), the current code created 2312 bytes across 63 memory allocations per flow record created (each record being comprised of 9 info elements, totaling 45 bytes when encoded).
In a hacked together rewrite of the core info element, set, and record functions to use explicit types and re-use buffers, I was able to get a version which resulted in 0 bytes across 0 memory allocations per flow in the same benchmark. This cut down the overall runtime by 35x.
While this modified version was by no means a complete API, it showcases the current overhead imposed by memory allocation and garbage collection. I believe that some level of optimization could be done on the current code to reduce the number of allocations per flow generated, hopefully getting closer to 0 per flow.

**Describe the solution you'd like**
The ability to generate Records (and the Info Elements which comprise them) via explicitly typed functions such that each data element (such as sourceIPv4Address of a flow) aren't kicked to the heap during each flow creation.
In addition, the ability to pass bytes.Buffers to Records (and maybe Sets) would greatly reduce the number of memory allocations and buffer grow() calls since currently these buffers are created fresh for each record, but these buffers typically end up reaching the same size each time and then get garbage collected. A sync.Pool could be used to coordinate a pool of record buffers that get re-used by processes that are generating flow records.

**Describe alternatives you've considered**
Disregard the overhead - Flows can still be created very quickly, and the current speed may be more than sufficient for any real world use cases. A single system may only have the need to generate a thousand flows per second, which could be achieved in 3 milliseconds on a single thread in my current setup. Systems with very limited resources, particularly memory, may encounter issues if garbage collection cannot keep up.
Force a specific structured flow message like https://github.com/cloudflare/goflow does using protobufs - Obvious restrictions imposed on the users, doesn't appear like that's a consideration for this project

**Additional context**

This post is more of a question than a feature request - is sacrificing some of the APIs simplicity granted by using the blank interface considered worth the performance improvements? Obviously it doesn't have to be a all-or-nothing decision, I believe there could be some level of mem allocation optimizations made with very minimal or no changes to the exported API.

#### Test/Benchmark setup
Messy benchmark code is at https://github.com/sheacloud/flowgen/blob/29c4615a75102ebbb8eeebdef5ec7a417a025d6d/cmd/benchmarking/benchmark_test.go
Modified go-ipfix used by above benchmark is at https://github.com/sheacloud/go-ipfix/commit/a72895045cd44d57bd9371754d672aa05e7c77d4

The modified code has plenty of broken features/oversights, it's just a quick demo of the raw performance of fundamental buffer writes/memory movement necessary for encoding the data into the records and sets, without any malloc overhead.

The benchmark was done using go test -bench, with each iteration of the benchmark generating N flow records, comprised of 9 fields, and adding them to a pre-existing Set. The benchmark does not send the Set as a message, it just writes endlessly to its buffer.
Benchmark results on current codebase:
![image](https://user-images.githubusercontent.com/20494388/101235478-edf23580-3696-11eb-9d37-ee81a67c2892.png)

Benchmark results on semi-modified codebase (still using blank interface, but certain redundant slice copies removed):
![image](https://user-images.githubusercontent.com/20494388/101235492-0f532180-3697-11eb-97e5-5a3f06b1d2b7.png)

Benchmark results on modified codebase:
![image](https://user-images.githubusercontent.com/20494388/101235481-fa768e00-3696-11eb-9667-c3105e10b82a.png)

I have started a new branch on my fork https://github.com/sheacloud/go-ipfix/tree/performance_improvements where I am writing non-breaking updates to try and test some of these changes. Currently I've got about a 50% decrease in both runtime and memory usage for Set.AddRecord() without changing any exported APIs, only internal things.

Appreciate any feedback on this topic, and I understand if the current flexibility offered by utilizing the blank interface outweighs the performance improvements of explicit typing. Thanks!

**Comment by srikartati** [comment]
Hi @sheacloud,
Thanks for creating the issue and looking at go-ipfix from a performance perspective. The analysis and insights look interesting-- we haven't focused on the performance aspect yet.
Went through the code on the fork and flowgen repo. I have a few questions and comments.

- Wondering if we reuse the [elements slice](https://github.com/sheacloud/flowgen/blob/29c4615a75102ebbb8eeebdef5ec7a417a025d6d/utils/exporter.go#L19) that was created during template generation when sending the data record rather than [creating one again](https://github.com/sheacloud/flowgen/blob/29c4615a75102ebbb8eeebdef5ec7a417a025d6d/utils/exporter.go#L93), will the memory allocs decrease? 

- Regarding the [usage of encodeToIEDataType](https://github.com/sheacloud/go-ipfix/commit/a72895045cd44d57bd9371754d672aa05e7c77d4#diff-0030409a3891d50163117119b39a7a95b76643345c548f7ab834879e961a4dceR202-R206), we also do the check if the added element is of expected type to encode or not. Users may give values with the wrong type. 

- [This change](https://github.com/sheacloud/go-ipfix/commit/1edd2ba71d99cce1f9f9d132593439c76fdb3fd4#diff-0030409a3891d50163117119b39a7a95b76643345c548f7ab834879e961a4dceR86-R94) definitely makes sense as we do not need to maintain the ordered elements list if we are encoding. I guess this is the semi-modified codebase. Please feel free to create a PR.

- Yes interface was used to support elements of all data types for both collector and exporter. We are definitely open if there is an alternate solution that gives better performance. As you mention the ease of use is important for the library and also we want users to have flexibility to create any template rather than a more restricted flow message format, for example, protobuf schema.
In that respect, we want to expose only the data set interface and not the record interface and its methods ideally. The plan is to use the record interface and methods internally. As we will extend the support to add multiple sets in one IPFIX message, it may get complex for users to use. If we can get the optimizations, adhering to the above objective, then that would be great.

**Comment by sheacloud** [comment]
Thank you for the feedback, @srikartati 
In response to the questions/comments:

- I'm not sure I'm following you, by template generation do you mean the creation of a template set that the user would presumably be creating before ever creating a record set, followed by the individual records? I think there could be some optimizations on the creation of records if the record set knew more about the template set that it was based upon, rather than just the template ID. I didn't come across anything that would easily allow for that, and I don't even know if it makes sense to force that order of operations on the user since creating a template after the records is fine so long as they send the template first. Having that template would mean that we could initialize most of the arrays to their correct size up front, plus do more validation that the IEs they were adding were in the correct order in relation to the template up front rather than at message send time.
- That makes sense. I'm curious what the intention of returning the val from the [encoding function](https://github.com/sheacloud/go-ipfix/blob/a1b92f6d33ae222c896b8b4ab4d52a0442269e34/pkg/entities/ie.go#L296-L302) is. To me it appears that "v" and "val" will always be the same, and the act of returning an interface pointer to the cast value "v" results in the value again be copied to the heap, whereas either just returning "val" or not returning a value at all prevents it. 
- That change did make probably the largest single improvement so I'll get it cleaned up, write some unit tests, and open a PR. I seem to recall seeing that idea mentioned somewhere in a previous issue so I'll see if I can find that again to reference.
- That last bit about the intention of only exposing the set helps a lot to understand what to work around. I'm thinking that keeping it with the interface makes the most sense right now but I'll continue testing a few alternative ideas and see if anything can keep the level of flexibility.

**Comment by srikartati** [comment]
> * I'm not sure I'm following you, by template generation do you mean the creation of a template set that the user would presumably be creating before ever creating a record set, followed by the individual records? I think there could be some optimizations on the creation of records if the record set knew more about the template set that it was based upon, rather than just the template ID. I didn't come across anything that would easily allow for that, and I don't even know if it makes sense to force that order of operations on the user since creating a template after the records is fine so long as they send the template first. Having that template would mean that we could initialize most of the arrays to their correct size up front, plus do more validation that the IEs they were adding were in the correct order in relation to the template up front rather than at message send time.

[ST] I just meant maintaining a list of elements that your [commented out line](https://github.com/sheacloud/flowgen/blob/29c4615a75102ebbb8eeebdef5ec7a417a025d6d/utils/exporter.go#L19) intended to do. They can be filled in when we send out the template. We could use those elements while sending the data set out rather than allocation a [new slice again](https://github.com/sheacloud/flowgen/blob/29c4615a75102ebbb8eeebdef5ec7a417a025d6d/utils/exporter.go#L93).

One more reference from Antrea, who is the main user of this library: https://github.com/vmware-tanzu/antrea/blob/master/pkg/agent/flowexporter/exporter/exporter.go#L74
This can save some unnecessary allocations.

> * That makes sense. I'm curious what the intention of returning the val from the [encoding function](https://github.com/sheacloud/go-ipfix/blob/a1b92f6d33ae222c896b8b4ab4d52a0442269e34/pkg/entities/ie.go#L296-L302) is. To me it appears that "v" and "val" will always be the same, and the act of returning an interface pointer to the cast value "v" results in the value again be copied to the heap, whereas either just returning "val" or not returning a value at all prevents it.

[ST] Yes, val is not needed. Feel free to remove it from the function in the PR you are working on. Thanks.

> * That last bit about the intention of only exposing the set helps a lot to understand what to work around. I'm thinking that keeping it with the interface makes the most sense right now but I'll continue testing a few alternative ideas and see if anything can keep the level of flexibility.

[ST] Thanks. It will be useful to have a benchmark test checked in into the folder pkg/test/ that helped this analysis. This can be extended to collector and intermediate processes too. As more code gets added, we could make sure performance of go-ipfix is not degrading. If you don't mind, please consider checking in the benchmark test too.

**Comment by srikartati** [comment]
The discussed issues were covered in this issue: https://github.com/vmware/go-ipfix/issues/209
Multiple PRs were raised and merged into main branch to reduce the allocations. In our perf tests, we saw a reduction of around 70%.

Closing this issue. If there any other performance concerns, please reopen it or raise another one.
