### ISSUE TITLE
Bug in update release assets workflow

### ISSUE THREAD

**Issue by srikartati** [vmware/go-ipfix#177]
**Describe the bug**
Job ".github/workflows/upload_release_assets.yml" failed.
This happened with recent changes: https://github.com/vmware/go-ipfix/pull/159/files#diff-314f5721aedc184c05aa1195086e561593d9dde5bf3fe4b7023a03742aa1dbe8

Also please check why this workflow ran without creating a new release and just by merging the PR.
**To Reproduce**
Merge any PR.

**Expected behavior**
The job should not run in the first place. If it runs with a new release, it should be successful. 

**Actual Behavior**
Failed with error: .github/workflows/upload_release_assets.yml : .github#L1
a step cannot have both the `uses` and `run` keys
https://github.com/vmware/go-ipfix/actions/runs/796895666

**Versions**
main branch ToT

**Additional context**
Opened it to not loose track.

**Comment by srikartati** [comment]
@heanlan could you look into this?

**Comment by heanlan** [comment]
> @heanlan could you look into this?

Sorry about the issue. I have opened a PR #180 with a fix in it. 

The error "a step cannot have both the `uses` and `run` keys" is because I wrongly put the `uses` key in the step named `Build assets`. I have corrected that by putting it at the beginning of the job. 

I have no idea why the `upload_release_assets` workflow action can be triggered by merging the PR. I also just found this action was triggered every time when I commit codes to the previous PR #159 . As defined at the top of the workflow, it should only be triggered when a release is created. The abnormal trigger probably has something to do with the error in it.
